[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$GamePath,

    [ValidateSet("auto", "es", "en", "fr")]
    [string]$Language = "auto",

    [ValidateSet("auto", "es_218", "en_213", "fr_212p1")]
    [string]$Profile = "auto"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceMod = Join-Path $projectRoot "mod\HardcoreNuzlocke"
$snippetPath = Join-Path $projectRoot "installer\preload-snippet.rb"

if (-not (Test-Path -LiteralPath $GamePath -PathType Container)) {
    throw "No existe la carpeta del juego: $GamePath"
}

$resolvedGamePath = (Resolve-Path -LiteralPath $GamePath).Path
$gameExe = Join-Path $resolvedGamePath "Game.exe"
$preloadPath = Join-Path $resolvedGamePath "preload.rb"
$mkxpPath = Join-Path $resolvedGamePath "mkxp.json"
$scriptsPath = Join-Path $resolvedGamePath "Data\Scripts.rxdata"

foreach ($requiredPath in @($gameExe, $preloadPath, $mkxpPath, $scriptsPath, $sourceMod, $snippetPath)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Falta un archivo o carpeta necesaria: $requiredPath"
    }
}

$profileLanguages = @{
    "es_218" = "es"
    "en_213" = "en"
    "fr_212p1" = "fr"
}
$languageProfiles = @{
    "es" = "es_218"
    "en" = "en_213"
    "fr" = "fr_212p1"
}

$detectionText = $resolvedGamePath.ToLowerInvariant()
if ($Profile -eq "auto") {
    if ($Language -ne "auto") {
        $Profile = $languageProfiles[$Language]
    }
    elseif ($detectionText -match '2[\.,]13|english|anglais') {
        $Profile = "en_213"
    }
    elseif ($detectionText -match '2[\.,]12|fran[cç]ais|french') {
        $Profile = "fr_212p1"
    }
    elseif ($detectionText -match '2[\.,]18|spanish|espa[nñ]ol') {
        $Profile = "es_218"
    }
    else {
        throw "No se pudo detectar la edición. Indica -Language es|en|fr o -Profile es_218|en_213|fr_212p1."
    }
}

$profileLanguage = $profileLanguages[$Profile]
if ($Language -eq "auto") {
    $Language = $profileLanguage
}
elseif ($Language -ne $profileLanguage) {
    throw "El idioma '$Language' no corresponde al perfil '$Profile' (idioma esperado: '$profileLanguage')."
}

$targetMod = Join-Path $resolvedGamePath "Mods\HardcoreNuzlocke"
New-Item -ItemType Directory -Path $targetMod -Force | Out-Null
Get-ChildItem -LiteralPath $sourceMod -Force | Copy-Item -Destination $targetMod -Recurse -Force

$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
$installProfilePath = Join-Path $targetMod "Config\install_profile.rb"
$installProfileText = @"
# encoding: UTF-8

# Generated by install.ps1 for this game installation.
module PZHardcoreNuzlocke
  module InstallConfig
    LANGUAGE = :$Language
    PROFILE = :$Profile
  end
end
"@
[System.IO.File]::WriteAllText($installProfilePath, $installProfileText, $utf8WithoutBom)

$backupPath = "$preloadPath.backup-before-pokemon-mods"
if (-not (Test-Path -LiteralPath $backupPath)) {
    Copy-Item -LiteralPath $preloadPath -Destination $backupPath
    Write-Host "Copia de seguridad creada: $backupPath"
}

$preloadText = [System.IO.File]::ReadAllText($preloadPath)
$snippetText = [System.IO.File]::ReadAllText($snippetPath).Trim()
$markerPattern = '(?ms)^\s*# BEGIN POKEMON_MODS HARDCORE_NUZLOCKE\s*$.*?^\s*# END POKEMON_MODS HARDCORE_NUZLOCKE\s*\r?\n?'
$preloadText = [System.Text.RegularExpressions.Regex]::Replace($preloadText, $markerPattern, "").TrimEnd()
# The 2.12/2.13 packages include a disabled legacy Zlib workaround that only
# becomes active when preloadScript is enabled. It references a missing MKXP
# constant and crashes before the game scripts can load. Remove that exact
# known block; the engine's original Zlib implementation remains available.
$brokenZlibPattern = '(?ms)^\s*# Fix for Zlib::StreamError/Zlib:DataError by \[ g f y \]\s*module Zlib\s*class Inflate\s*def self\.inflate\(string\)\s*MKXP\.zinflate\(string\)\s*end\s*end\s*class Deflate\s*def self\.deflate\(string, level = 0\)\s*MKXP\.zdeflate\(string\)\s*end\s*end\s*end\s*'
$preloadText = [System.Text.RegularExpressions.Regex]::Replace($preloadText, $brokenZlibPattern, "").TrimEnd()
$hasExistingLoader = $preloadText -match '(?is)Mods.*HardcoreNuzlocke.*loader\.rb'
if ($hasExistingLoader) {
    $updatedPreload = $preloadText + [Environment]::NewLine
    Write-Host "Se reutiliza el cargador existente de Pokemon Z Mods."
}
else {
    $updatedPreload = $preloadText + [Environment]::NewLine + [Environment]::NewLine + $snippetText + [Environment]::NewLine
}
[System.IO.File]::WriteAllText($preloadPath, $updatedPreload, $utf8WithoutBom)

$mkxpBackupPath = "$mkxpPath.backup-before-pokemon-mods"
if (-not (Test-Path -LiteralPath $mkxpBackupPath)) {
    Copy-Item -LiteralPath $mkxpPath -Destination $mkxpBackupPath
    Write-Host "Copia de seguridad creada: $mkxpBackupPath"
}

$mkxpText = [System.IO.File]::ReadAllText($mkxpPath)
$preloadPattern = '(?m)^(?!\s*//)\s*"preloadScript"\s*:\s*\[(?<items>[^\]]*)\]'
$preloadMatch = [System.Text.RegularExpressions.Regex]::Match($mkxpText, $preloadPattern)
if ($preloadMatch.Success) {
    if ($preloadMatch.Groups["items"].Value -notmatch '(?i)["'']preload\.rb["'']') {
        $items = $preloadMatch.Groups["items"].Value.Trim()
        $newItems = if ($items.Length -eq 0) { '"preload.rb"' } else { "$items, `"preload.rb`"" }
        $replacement = $preloadMatch.Value.Substring(0, $preloadMatch.Value.IndexOf('[') + 1) + $newItems + ']'
        $mkxpText = $mkxpText.Substring(0, $preloadMatch.Index) + $replacement + $mkxpText.Substring($preloadMatch.Index + $preloadMatch.Length)
    }
}
else {
    $mkxpMarker = "// BEGIN POKEMON_MODS PRELOAD$([Environment]::NewLine)  `"preloadScript`": [`"preload.rb`"],$([Environment]::NewLine)  // END POKEMON_MODS PRELOAD"
    $openingBrace = $mkxpText.IndexOf('{')
    if ($openingBrace -lt 0) {
        throw "mkxp.json no contiene un objeto JSON válido: $mkxpPath"
    }
    $mkxpText = $mkxpText.Insert($openingBrace + 1, [Environment]::NewLine + "  " + $mkxpMarker)
}
[System.IO.File]::WriteAllText($mkxpPath, $mkxpText, $utf8WithoutBom)

Write-Host ""
Write-Host "Pokemon Z Mods se ha instalado correctamente." -ForegroundColor Green
Write-Host "Juego: $resolvedGamePath"
Write-Host "Mod:   $targetMod"
Write-Host "Idioma: $Language"
Write-Host "Perfil: $Profile"
Write-Host ""
Write-Host "Inicia Game.exe. Tras llegar al menu principal, revisa este registro:"
Write-Host (Join-Path $targetMod "nuzlocke.log")
Write-Host "La validacion correcta termina con: PASS (13 hooks)"
