# encoding: UTF-8

module PZHardcoreNuzlocke
  module Config
    # Logical encounter areas. Floors and linked interiors that form a single
    # route/cave deliberately share an entry. Unknown maps safely fall back to
    # their own map id, so the mod remains compatible with future map additions.
    AREAS = {
      :pueblo_lienzo              => ["Pueblo Lienzo", [3, 504]],
      :pueblo_petroglifo          => ["Pueblo Petroglifo", [102]],
      :ruta_1                     => ["Ruta 1", [7]],
      :pueblo_vinilo              => ["Pueblo Vinilo", [9]],
      :catacumbas_meridionales    => ["Catacumbas Meridionales", [47]],
      :ruta_2                     => ["Ruta 2", [14, 52]],
      :cueva_grisalla             => ["Cueva Grisalla", [16, 54]],
      :ciudad_grisalla            => ["Ciudad Grisalla", [17]],
      :ruta_3                     => ["Ruta 3", [23, 53]],
      :pueblo_acrilico            => ["Pueblo Acrílico", [24]],
      :ruta_4                     => ["Ruta 4", [27]],
      :bosque_ladera              => ["Bosque Ladera", [28, 46]],
      :pueblo_collage             => ["Pueblo Collage", [29]],
      :ruta_5                     => ["Ruta 5", [55, 56]],
      :santuario_reyes            => ["Santuario de los Reyes", [58]],
      :ciudad_oleo                => ["Ciudad Óleo", [59]],
      :chateau_rosillon           => ["Château Rosillon", [36]],
      :vieja_biblioteca           => ["Vieja Biblioteca", [39]],
      :ruta_6                     => ["Ruta 6", [41, 70]],
      :pueblo_profano             => ["Pueblo Profano", [42]],
      :pantano_profano            => ["Pantano Profano", [43, 44, 57]],
      :cueva_lobrega              => ["Cueva Lóbrega", [45, 200]],
      :ruta_7_norte               => ["Ruta 7 Norte", [76]],
      :cueva_refulgente           => ["Cueva Refulgente", [51, 78]],
      :ruta_7_sur                 => ["Ruta 7 Sur", [79]],
      :ciudad_novarte             => ["Ciudad Novarte", [80]],
      :colina_tormenta            => ["Colina Tormenta", [99]],
      :taller_quemado             => ["Taller Quemado", [81]],
      :ruta_8                     => ["Ruta 8", [91, 100, 165]],
      :santuario_prosperidad      => ["Santuario de la Prosperidad", [118]],
      :ruta_9                     => ["Ruta 9", [97, 103, 121]],
      :ruta_10                    => ["Ruta 10", [96]],
      :ruta_11                    => ["Ruta 11", [107, 110]],
      :isla_certijo               => ["Isla Certijo", [123]],
      :catacumbas_septentrionales => ["Catacumbas Septentrionales", [128]],
      :ciudad_relieve             => ["Ciudad Relieve", [133]],
      :gruta_tierraunida          => ["Gruta Tierraunida", [136]],
      :ruta_12                    => ["Ruta 12", [137]],
      :viejo_vanitas              => ["Viejo Vanitas", [138, 139, 140]],
      :pueblo_vanitas             => ["Pueblo Vanitas", [141]],
      :ruta_13                    => ["Ruta 13", [157, 159]],
      :ciudad_luminalia           => ["Ciudad Luminalia", [162]],
      :bastion_pokemon            => ["Bastión Pokémon", [146]],
      :criptas_luminalia          => ["Criptas de Luminalia", [186]],
      :prision_olvido             => ["Prisión del Olvido", [222, 223]],
      :sima_ardiente              => ["Sima Ardiente", [229, 349]],
      :pirineos                   => ["Pirineos", [255, 256, 257, 258]],
      :ciudad_batik               => ["Ciudad Batik", [247]],
      :estacion_servicio          => ["Estación de Servicio", [130]],
      :ruta_14                    => ["Ruta 14", [269]],
      :ciudad_romantis            => ["Ciudad Romantis", [233]],
      :fabrica_pokeball           => ["Fábrica de Poké Balls", [232]],
      :ruta_15                    => ["Ruta 15", [234, 270]],
      :ruta_16                    => ["Ruta 16", [237, 284]],
      :ruta_17                    => ["Ruta 17", [242]],
      :gruta_helada               => ["Gruta Helada", [238, 243, 245]],
      :pueblo_fresco              => ["Pueblo Fresco", [283]],
      :ruta_18                    => ["Ruta 18", [287, 288]],
      :ciudad_fluxus              => ["Ciudad Fluxus", [297]],
      :ruta_19                    => ["Ruta 19", [299]],
      :cueva_desenlace            => ["Cueva Desenlace", [300, 301, 303]],
      :pueblo_mosaico             => ["Pueblo Mosaico", [290]],
      :ruta_20                    => ["Ruta 20", [292]],
      :ciudad_fractal             => ["Ciudad Fractal", [310]],
      :isla_montesanto            => ["Isla Montesanto", [230, 231, 315]],
      :fondo_lago                 => ["Fondo del Lago", [323, 324]],
      :antigua_forja              => ["Antigua Forja", [298, 318]],
      :catacumbas_orientales      => ["Catacumbas Orientales", [330]],
      :fondo_marino_acrilico      => ["Fondo Marino de Acrílico", [335]],
      :fondo_marino_petroglifo    => ["Fondo Marino de Petroglifo", [336]],
      :fondo_lago_ruta_16         => ["Fondo del Lago de Ruta 16", [337]],
      :batalla_kalos_este         => ["Batalla de Kalos Este", [314]],
      :ruta_21                    => ["Ruta 21", [339]],
      :bosque_errante             => ["Bosque Errante", [353, 365, 366, 367, 368, 369, 370, 371, 372]],
      :ruta_22                    => ["Ruta 22", [358, 359]],
      :pueblo_sanguino            => ["Pueblo Sanguino", [360]],
      :expansiones_luminalia      => ["Expansiones de Luminalia", [361, 391]],
      :ruta_23                    => ["Ruta 23", [354, 373]],
      :ruta_24                    => ["Ruta 24", [376]],
      :catacumbas_occidentales    => ["Catacumbas Occidentales", [401, 403]],
      :ciudad_yantra              => ["Ciudad Yantra", [381, 382, 461, 462]],
      :lugar_misterioso           => ["Lugar Misterioso", [412]],
      :cueva_reflejos             => ["Cueva de los Reflejos", [420, 465]],
      :ruta_25                    => ["Ruta 25", [414, 421, 466, 467, 479, 483, 484, 485]],
      :villa_pokemon              => ["Villa Pokémon", [356]],
      :bahia_azul                 => ["Bahía Azul", [432]],
      :costa_sanguina             => ["Costa Sanguina", [444]],
      :arma_definitiva            => ["Arma Definitiva", [471]],
      :ruta_26                    => ["Ruta 26", [487]]
    }
  end
end
