#!/usr/bin/env python3
"""Cross-platform installer for Pokemon Z Mods.

This installer only copies the mod and updates preload.rb/mkxp.json. It never
edits Data/Scripts.rxdata or save files.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import sys
from pathlib import Path


PROFILE_LANGUAGES = {
    "es_218": "es",
    "en_213": "en",
    "fr_212p1": "fr",
}
LANGUAGE_PROFILES = {value: key for key, value in PROFILE_LANGUAGES.items()}
KNOWN_SCRIPTS_PROFILES = {
    "0580b2f2787c16fcbc72f6cd34155656102985f43d92a560a34232e64dea9001": "es_218",
    "82ac875ca31a2b9b32f046c965e5f89dda8b479ec768d3ca2b90125943dbdfee": "en_213",
    "4af6e9e7ead84e439c3ec05451dcfac46b06b70c6160e8e99f6207d18209c1b4": "fr_212p1",
}


def detect_profile(game_path: Path, language: str, profile: str) -> tuple[str, str]:
    if profile != "auto":
        expected_language = PROFILE_LANGUAGES[profile]
        if language not in ("auto", expected_language):
            raise ValueError(
                f"Language '{language}' does not match profile '{profile}' "
                f"(expected '{expected_language}')."
            )
        return profile, expected_language

    if language != "auto":
        return LANGUAGE_PROFILES[language], language

    scripts_path = game_path / "Data" / "Scripts.rxdata"
    if scripts_path.is_file():
        digest = hashlib.sha256(scripts_path.read_bytes()).hexdigest()
        detected_profile = KNOWN_SCRIPTS_PROFILES.get(digest)
        if detected_profile:
            return detected_profile, PROFILE_LANGUAGES[detected_profile]

    detection = str(game_path).lower()
    if re.search(r"2[.,]13|english|anglais", detection):
        return "en_213", "en"
    if re.search(r"2[.,]12|fran[cç]ais|french", detection):
        return "fr_212p1", "fr"
    if re.search(r"2[.,]18|spanish|espa[nñ]ol", detection):
        return "es_218", "es"
    raise ValueError(
        "The game edition could not be detected from its files or folder name. "
        "Pass --profile es_218, en_213 or fr_212p1."
    )


def remove_known_blocks(preload_text: str) -> str:
    marker_pattern = re.compile(
        r"(?ms)^\s*# BEGIN POKEMON_MODS HARDCORE_NUZLOCKE\s*$.*?"
        r"^\s*# END POKEMON_MODS HARDCORE_NUZLOCKE\s*\r?\n?"
    )
    preload_text = marker_pattern.sub("", preload_text).rstrip()

    broken_zlib_pattern = re.compile(
        r"(?ms)^\s*# Fix for Zlib::StreamError/Zlib:DataError by \[ g f y \]\s*"
        r"module Zlib\s*class Inflate\s*def self\.inflate\(string\)\s*"
        r"MKXP\.zinflate\(string\)\s*end\s*end\s*class Deflate\s*"
        r"def self\.deflate\(string, level = 0\)\s*MKXP\.zdeflate\(string\)\s*"
        r"end\s*end\s*end\s*"
    )
    return broken_zlib_pattern.sub("", preload_text).rstrip()


def update_mkxp(mkxp_text: str) -> str:
    preload_pattern = re.compile(
        r'(?m)^(?!\s*//)\s*"preloadScript"\s*:\s*\[(?P<items>[^\]]*)\]'
    )
    match = preload_pattern.search(mkxp_text)
    if match:
        if not re.search(r'["\']preload\.rb["\']', match.group("items"), re.I):
            items = match.group("items").strip()
            new_items = '"preload.rb"' if not items else f'{items}, "preload.rb"'
            replacement = match.group(0).split("[", 1)[0] + "[" + new_items + "]"
            mkxp_text = mkxp_text[: match.start()] + replacement + mkxp_text[match.end() :]
        return mkxp_text

    opening_brace = mkxp_text.find("{")
    if opening_brace < 0:
        raise ValueError("mkxp.json does not contain a valid object.")
    marker = (
        '\n  // BEGIN POKEMON_MODS PRELOAD\n'
        '  "preloadScript": ["preload.rb"],\n'
        '  // END POKEMON_MODS PRELOAD'
    )
    return mkxp_text[: opening_brace + 1] + marker + mkxp_text[opening_brace + 1 :]


def install(game_path: Path, language: str, profile: str) -> None:
    project_root = Path(__file__).resolve().parent.parent
    source_mod = project_root / "mod" / "HardcoreNuzlocke"
    snippet_path = project_root / "installer" / "preload-snippet.rb"
    required = [
        game_path / "Game.exe",
        game_path / "preload.rb",
        game_path / "mkxp.json",
        game_path / "Data" / "Scripts.rxdata",
        source_mod,
        snippet_path,
    ]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("Required files are missing:\n" + "\n".join(missing))

    profile, language = detect_profile(game_path, language, profile)
    target_mod = game_path / "Mods" / "HardcoreNuzlocke"
    target_mod.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source_mod, target_mod, dirs_exist_ok=True)

    install_profile = f'''# encoding: UTF-8

# Generated by the cross-platform Pokemon Z Mods installer.
module PZHardcoreNuzlocke
  module InstallConfig
    LANGUAGE = :{language}
    PROFILE = :{profile}
  end
end
'''
    (target_mod / "Config" / "install_profile.rb").write_text(
        install_profile, encoding="utf-8"
    )

    preload_path = game_path / "preload.rb"
    preload_backup = game_path / "preload.rb.backup-before-pokemon-mods"
    if not preload_backup.exists():
        shutil.copy2(preload_path, preload_backup)
    preload_text = remove_known_blocks(preload_path.read_text(encoding="utf-8-sig"))
    snippet = snippet_path.read_text(encoding="utf-8-sig").strip()
    if not re.search(r"Mods.*HardcoreNuzlocke.*loader\.rb", preload_text, re.I | re.S):
        preload_text = (preload_text + "\n\n" + snippet).lstrip("\n")
    preload_path.write_text(preload_text.rstrip() + "\n", encoding="utf-8")

    mkxp_path = game_path / "mkxp.json"
    mkxp_backup = game_path / "mkxp.json.backup-before-pokemon-mods"
    if not mkxp_backup.exists():
        shutil.copy2(mkxp_path, mkxp_backup)
    mkxp_text = mkxp_path.read_text(encoding="utf-8-sig")
    mkxp_path.write_text(update_mkxp(mkxp_text), encoding="utf-8")

    print("Pokemon Z Mods installed successfully.")
    print(f"Game:     {game_path}")
    print(f"Mod:      {target_mod}")
    print(f"Language: {language}")
    print(f"Profile:  {profile}")
    print("Start the game and check Mods/HardcoreNuzlocke/nuzlocke.log.")
    print("A correct installation reports: PASS (14 hooks)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Install Pokemon Z Mods.")
    parser.add_argument("game_path", nargs="?", help="Folder containing Game.exe")
    parser.add_argument("--language", choices=["auto", "es", "en", "fr"], default="auto")
    parser.add_argument(
        "--profile",
        choices=["auto", "es_218", "en_213", "fr_212p1"],
        default="auto",
    )
    args = parser.parse_args()
    game_path_text = args.game_path or input("Pokemon Z folder containing Game.exe: ").strip()
    if not game_path_text:
        parser.error("A game folder is required.")
    try:
        install(Path(game_path_text).expanduser().resolve(), args.language, args.profile)
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
